### ISSUE TITLE
Automate configuration process

### ISSUE THREAD

**Issue by mohdomama** [pimutils/todoman#300] opened 2018-01-21 14:23 UTC
As of now, when todoman is run the first time, you have to manually add the `todoman.conf` file in `~/.config/todoman/`. Also in the config file we have to specify the `path` where our ics lists (folders) are. 
It will be nice if we can make a script that creates the default configurations for the user. The script may do the following :
- Check if `~/.config/todoman/todoman.conf` exists. If it doesn't, create it with default configuration.
- The default path can be something like `~/todoman/*`. The script would have to create this folder.
- Within the `path` , there should me a directory called `DefaultList`. The script would have to create that too.

This will allows any new user to try todoman, without going through the tiring process of manual configuration. Later, the user can edit default configurations if he wants.

**Comment by untitaker** [comment] 2018-01-21 16:10
Duplicate of https://github.com/pimutils/todoman/issues/129

**Closed** 2018-01-21 16:11 UTC
