### ISSUE TITLE
Stack Trace in Usage Docs

### ISSUE THREAD

**Issue by rsynnest** [pimutils/todoman#414] opened 2020-11-28 21:27 UTC
Wanted to check out this project, went to the Usage section of the docs, which greets me with this:

![Screenshot_20201128-132345](https://user-images.githubusercontent.com/4392850/100526391-3e403380-317d-11eb-959f-15c948c037c1.png)

I assume some bug in autogenerated docs caused this, I'm on mobile so can't dig into it.

**Comment by WhyNotHugo** [comment] 2020-11-28 21:46
Duplicate of #393

**Closed by WhyNotHugo** 2020-11-28 21:46 UTC
