### ISSUE TITLE
No sample configuration file is present

### ISSUE THREAD

**Issue by rimshaakhan** [pimutils/todoman#107] opened 2017-02-19 17:28 UTC
There is no sample configuration file in [configure.rst](https://github.com/pimutils/todoman/blob/master/docs/configure.rst) though there is an [heading](https://github.com/pimutils/todoman/blob/master/docs/configure.rst#sample-configuration) for the former!

**Comment by hobarrera** [comment] 2017-02-19 18:02
`configure.rst` is used to build [this](http://todoman.readthedocs.io/en/stable/configure.html) page. If you look at `configure.rst`'s source, you'll see that it has an include directive (which GitHub doesn't parse for its preview).

Feel free to reply here if you have further questions regarding this, but I'll close the issue since it's all working as intended.

**Closed by hobarrera** 2017-02-19 18:02 UTC
