### ISSUE TITLE
list names are not appearing in color

### ISSUE THREAD

**Issue by RJ722** [pimutils/todoman#251] opened 2017-06-14 19:21 UTC
Hello!

When I changed my machine recently, lists stop appearing coloured. I am not sure if this is OS related because I have shifted from Linux (zsh) -> Mac OS X (zsh). Other than this, other colors are working, for eg.: the todo's date turns red after deadline.

Additional information:
* tree structure for lists.
```
/Users/rahuljha/.local/share/calendars/
├── GSoC
│   ├── 05dd381815ef4871acf4f8965d91b35f@Rahuls-Air.ics
│   ├── 591333af7e3d4bf3a1b9ab0a2da7adc4@Rahuls-MacBook-Air.local.ics
│   ├── 5a3db5189cd54633a32027e82cfeb7d7@Rahuls-MacBook-Air.local.ics
│   ├── 5c6c9ac08af644cfb8bb8161e3d21951@Rahuls-Air.ics
│   ├── 7b5887892e9e4a289f4d748cc5db3c57@Rahuls-Air.ics
│   ├── 8f6008c8cb27407bbe2d6584e73348d0@Rahuls-MacBook-Air.local.ics
│   ├── color
│   ├── colour
│   ├── dbb77643a9c74e7798fc5e777f37853d@Rahuls-MacBook-Air.local.ics
│   └── edb7c18ccd724d9b9c859353f822e779@Rahuls-MacBook-Air.local.ics
├── OSS
│   ├── 07f74e13d1ae4455a4cefa0a723e4366@Rahuls-MacBook-Air.local.ics
│   ├── 6dd2ec793a884c05bb7263c82df2b087@Rahuls-Air.ics
│   └── color
├── Personal
│   ├── 853f094fa4cf4df3a29ef704ee17ee11@Rahuls-Air.ics
│   ├── 945c1d32674d4f6f800405f1a5b2d836@Rahuls-Air.ics
│   ├── aece4e1db3ee4e35902d95748dd247a7@Rahuls-Air.ics
│   ├── c1c460670979432eb52b00e7fdfae9dc@Rahuls-Air.ics
│   ├── color
│   └── dd3c23d2360a44f3bc0b1fdedd43042c@Rahuls-Air.ics
├── Roboclub
│   ├── 3079ece5d53e4b28b3a122f77d32e80e@Rahuls-Air.ics
│   └── color
└── chores
    ├── 79c80aefbcee4432b62b3b95849ff238@Rahuls-MacBook-Air.local.ics
    ├── 9a952ef7af5d4a8dbd11ad9b0d66037c@Rahuls-Air.ics
    ├── a3133825bb444a4aa6eb51ea7491d308@Rahuls-Air.ics
    ├── bd9d1a7b035847f38acd7d41fe213f7d@Rahuls-MacBook-Air.local.ics
    └── color

5 directories, 26 files
```
I even tried renaming the file to `colour` 😆 
* Output of `cat ~/.local/share/calendars/**/*color`
```
#00FF00
#ff0000
#ff00ff
#00ff00
#0000FF
```

* Should I also upload a screenshot?

Thank you for such an awesome product!

**Comment by RJ722** [comment] 2017-06-14 19:56
IMHO it's probably because of some sort of encoding error.

I did a little experiment:
I installed todoman in an empty virtualenv, set up dev and docs requirements and bam:
```
78 failed, 76 passed, 1 skipped, 3 xfailed in 133.11 seconds
```
All of them had an error message similar to:
```
E       AssertionError: assert not RuntimeError('Click will abort further execution because Python 3 was configured to use ASCII as encoding for the envi... sk_SK.UTF-8, sl_SI.UTF-8, sr_YU.UTF-8, sv_SE.UTF-8, tr_TR.UTF-8, uk_UA.UTF-8, zh_CN.UTF-8, zh_HK.UTF-8, zh_TW.UTF-8',)
E        +  where RuntimeError('Click will abort further execution because Python 3 was configured to use ASCII as encoding for the envi... sk_SK.UTF-8, sl_SI.UTF-8, sr_YU.UTF-8, sv_SE.UTF-8, tr_TR.UTF-8, uk_UA.UTF-8, zh_CN.UTF-8, zh_HK.UTF-8, zh_TW.UTF-8',) = <Result RuntimeError('Click will abort further execution because Python 3 was configured to use ASCII as encoding for ...sk_SK.UTF-8, sl_SI.UTF-8, sr_YU.UTF-8, sv_SE.UTF-8, tr_TR.UTF-8, uk_UA.UTF-8, zh_CN.UTF-8, zh_HK.UTF-8, zh_TW.UTF-8',)>.exception
```
Along with a log:
```
# Sphinx version: 1.6.2
# Python version: 3.6.1 (CPython)
# Docutils version: 0.13.1 release
# Jinja2 version: 2.9.6
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "/Users/rahuljha/Documents/todoman/.tox/docs/lib/python3.6/site-packages/sphinx/cmdline.py", line 305, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/Users/rahuljha/Documents/todoman/.tox/docs/lib/python3.6/site-packages/sphinx/application.py", line 168, in __init__
    confoverrides or {}, self.tags)
  File "/Users/rahuljha/Documents/todoman/.tox/docs/lib/python3.6/site-packages/sphinx/config.py", line 150, in __init__
    execfile_(filename, config)
  File "/Users/rahuljha/Documents/todoman/.tox/docs/lib/python3.6/site-packages/sphinx/util/pycompat.py", line 150, in execfile_
    exec_(code, _globals)
  File "conf.py", line 95, in <module>
  File "conf.py", line 46, in write_section
UnicodeEncodeError: 'ascii' codec can't encode character '\u2019' in position 59: ordinal not in range(128)
```
I can't really make a lot of sense out of it atm.
FWIW, my terminal is using `UTF-8` text-encoding.

**Comment by hobarrera** [comment] 2017-06-14 20:17
Hmm... Not entirely sure what the issue is yet, can you:

* Run `echo "\033[0;36mBLAH"`. Is this colourized? It probably should be, since I don't think the issue is with your terminal.
* Can you paste the output of `env`? I'd like to see if there's any odd language/encoding settings that might get in the way.

TBH, none of the devs use macOS, but I _think_ some users do. FWIW, test run fine on macOS on travis, so it should work just fine. I've no problem supporting it if you're willing to provide the feedback required though.

**Comment by RJ722** [comment] 2017-06-14 20:22
> Run echo "\033[0;36mBLAH". Is this colourized? It probably should be, since I don't think the issue is with your terminal.

It indeed is colored.

Here's the output of `env`:
```
TMPDIR=/var/folders/9p/6q_p_sjj7h3_ywvv8jdzvw500000gn/T/
TERM_PROGRAM_VERSION=388
Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.oz7nUoXxdQ/Render
LC_CTYPE=UTF-8
TERM_PROGRAM=Apple_Terminal
XPC_SERVICE_NAME=0
XPC_FLAGS=0x0
TERM_SESSION_ID=3F4B3CD8-427A-41DC-A051-6D07D36378AF
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.NyxqWIlghV/Listeners
TERM=xterm-256color
__CF_USER_TEXT_ENCODING=0x1F5:0x0:0x0
SHELL=/bin/zsh
HOME=/Users/rahuljha
LOGNAME=rahuljha
USER=rahuljha
PATH=/Users/rahuljha/.virtualenvs/coala_dev/bin:/Users/rahuljha/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
SHLVL=1
PWD=/Users/rahuljha/Documents
OLDPWD=/Users/rahuljha/Documents/vulture
ZSH=/Users/rahuljha/.oh-my-zsh
PAGER=less
LESS=-R
LSCOLORS=Gxfxcxdxbxegedabagacad
WORKON_HOME=/Users/rahuljha/.virtualenvs
VIRTUALENVWRAPPER_PROJECT_FILENAME=.project
VIRTUALENVWRAPPER_WORKON_CD=1
VIRTUALENVWRAPPER_SCRIPT=/usr/local/bin/virtualenvwrapper.sh
VIRTUALENVWRAPPER_HOOK_DIR=/Users/rahuljha/.virtualenvs
PS1=(coala_dev) ${ret_status} %{$fg[cyan]%}%c%{$reset_color%} $(git_prompt_info)
VIRTUAL_ENV=/Users/rahuljha/.virtualenvs/coala_dev
_=/usr/bin/env
```

> TBH, none of the devs use macOS, but I think some users do. FWIW, test run fine on macOS on travis, so it should work just fine. I've no problem supporting it if you're willing to provide the feedback required though.

Thank You very much @hobarrera ! I will be actively providing any information and feedback you might need 😄

**Comment by hobarrera** [comment] 2017-06-14 20:58
Hm, so merely setting `LC_CTYPE=UTF-8` for me reproduces the issues you see on tests, so I'll try to work from that.

**Comment by RJ722** [comment] 2017-06-14 21:23
I changed `LC_CTYPE` to `en_US.UTF-8` now, tests appear to go fine now, but the lists aren't coloured yet 😕

**Comment by RJ722** [comment] 2017-06-21 10:09
Just switching from terminal to iTerm2 got me the coloured output.

I will try and investigate the differences, what should I look for?

**Comment by untitaker** [comment] 2017-06-21 11:23
could you output `env | grep LC` and `env | grep LANG` in both?

**Comment by RJ722** [comment] 2017-06-21 12:17
`env | grep LC` gives `LC_CTYPE=UTF-8` in both.

Here's the output of env:

on terminal:
```
TMPDIR=/var/folders/9p/6q_p_sjj7h3_ywvv8jdzvw500000gn/T/
TERM_PROGRAM_VERSION=388
Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.MfTzoKOEQH/Render
LC_CTYPE=UTF-8
TERM_PROGRAM=Apple_Terminal
XPC_SERVICE_NAME=0
XPC_FLAGS=0x0
DISPLAY=/private/tmp/com.apple.launchd.JHNQoP8UHS/org.macosforge.xquartz:0
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.5Of11j14Jg/Listeners
TERM=xterm-256color
TERM_SESSION_ID=DD82BAF7-816E-42F1-BA5D-F8118CD7BE13
__CF_USER_TEXT_ENCODING=0x1F5:0x0:0x0
SHELL=/bin/zsh
HOME=/Users/rahuljha
LOGNAME=rahuljha
USER=rahuljha
PATH=/Users/rahuljha/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin
SHLVL=1
PWD=/Users/rahuljha
OLDPWD=/Users/rahuljha
ZSH=/Users/rahuljha/.oh-my-zsh
PAGER=less
LESS=-R
LSCOLORS=Gxfxcxdxbxegedabagacad
WORKON_HOME=/Users/rahuljha/.virtualenvs
VIRTUALENVWRAPPER_PROJECT_FILENAME=.project
VIRTUALENVWRAPPER_WORKON_CD=1
VIRTUALENVWRAPPER_SCRIPT=/usr/local/bin/virtualenvwrapper.sh
VIRTUALENVWRAPPER_HOOK_DIR=/Users/rahuljha/.virtualenvs
_=/usr/bin/env
```

on iTerm2:
```
TERM_SESSION_ID=w0t0p1:12C68B73-7A05-4C4D-9CEA-8EA7D6722573
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.5Of11j14Jg/Listeners
Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.MfTzoKOEQH/Render
COLORFGBG=7;0
ITERM_PROFILE=Default
XPC_FLAGS=0x0
PWD=/Users/rahuljha
SHELL=/bin/zsh
LC_CTYPE=UTF-8
TERM_PROGRAM_VERSION=3.0.15
TERM_PROGRAM=iTerm.app
PATH=/Users/rahuljha/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin
DISPLAY=/private/tmp/com.apple.launchd.JHNQoP8UHS/org.macosforge.xquartz:0
TERM=xterm-256color
HOME=/Users/rahuljha
TMPDIR=/var/folders/9p/6q_p_sjj7h3_ywvv8jdzvw500000gn/T/
USER=rahuljha
XPC_SERVICE_NAME=0
LOGNAME=rahuljha
ITERM_SESSION_ID=w0t0p1:12C68B73-7A05-4C4D-9CEA-8EA7D6722573
__CF_USER_TEXT_ENCODING=0x1F5:0x0:0x0
SHLVL=1
OLDPWD=/Users/rahuljha
ZSH=/Users/rahuljha/.oh-my-zsh
PAGER=less
LESS=-R
LSCOLORS=Gxfxcxdxbxegedabagacad
WORKON_HOME=/Users/rahuljha/.virtualenvs
VIRTUALENVWRAPPER_PROJECT_FILENAME=.project
VIRTUALENVWRAPPER_WORKON_CD=1
VIRTUALENVWRAPPER_SCRIPT=/usr/local/bin/virtualenvwrapper.sh
VIRTUALENVWRAPPER_HOOK_DIR=/Users/rahuljha/.virtualenvs
_=/usr/bin/env
```

**Comment by RJ722** [comment] 2017-06-21 18:56
Oh! A new **Update**:

Though the output is colored now, I **can't change the color**!

The colors which are there are those which I had before installing iTerm2 (those which are mentioned above)

**Comment by aleprovencio** [comment] 2018-01-18 20:20
What colors besides due dates should be shown, I am missing something? I have khal showing all the colors even detecting them through metadata for each of my calendars, but can't see any of that on todoman. Can any of you please put a screenshot?

**Comment by untitaker** [comment] 2018-01-18 20:30
![2018-01-18-212817_635x74_scrot](https://user-images.githubusercontent.com/837573/35119913-b6d50114-fc96-11e7-8117-5e01332450fa.png)

Try switching to iTerm 2, I think it's an issue with RGB colorcodes not being supported by the other terminals

**Comment by untitaker** [comment] 2018-01-18 20:32
Looking back at this it's obvious what the issue is: your terminal doesn't support the ansi codes we use to produce full RGB colors. vte3-based terminals on Linux and iTerm 2 apparently do support that.

We should document this.

**Comment by aleprovencio** [comment] 2018-01-18 21:12
thanks @untitaker, I indeed don't see such colors. Weird fact is that i run termite which is vte-based. Anything I can do to help debugging this?

**Comment by untitaker** [comment] 2018-01-18 21:38
Oh, I thought you were on a Mac. I am on Termite too.

**Comment by untitaker** [comment] 2018-01-18 21:41
closing for #297

**Closed by untitaker** 2018-01-18 21:41 UTC

**Comment by WhyNotHugo** [comment] 2018-01-18 21:57
Actually, I think you've found a bug!

If a whole list is cached before running `vdirsyncer metasync`, and then you run `todo`, it'll never expire that cache, and will never pick up the new colour information.

Nice corner case you've found here!

**Comment by aleprovencio** [comment] 2018-01-18 23:37
That is cool, glad I could help somehow. :)

**Comment by WhyNotHugo** [comment] 2018-01-20 15:47
I've opened #251 to follow up on that specifically.

**Comment by aleprovencio** [comment] 2018-01-22 16:34
I guess you meant [#298](https://github.com/pimutils/todoman/issues/298).

**Comment by WhyNotHugo** [comment] 2018-01-24 04:28
Yup, my bad!

**Comment by potuz** [comment] 2018-09-03 13:01
I apologize if it's not the right channel to ask for help, but is it rxvt-unicode compatible with this? The command ``echo "\033[0;36mBLAH"`` will not come colorized but something like
```
perl -e 'print "\033[48;5;168mBlah\033[0m\n"';
```
Does print in color.

**Comment by WhyNotHugo** [comment] 2018-09-05 16:45
Apparently, there seem to be some caveats regarding `urxvt` and truecolor support. But it _should_ be supported (even though you might only get approximate colour).

See here for details: https://gist.github.com/XVilka/8346728#gistcomment-2184965

Can you try using this script and check that colours work as expected?

https://raw.githubusercontent.com/JohnMorales/dotfiles/master/colors/24-bit-color.sh

**Comment by potuz** [comment] 2018-09-06 00:03
Ah right I didn't even know about this 24-bit-color branch of urxvt. I have only a 256-color terminal configured. I'll try to compile that branch and get back here. Thanks!

**Comment by potuz** [comment] 2018-09-15 10:38
> Can you try using this script and check that colours work as expected?
> 
> https://raw.githubusercontent.com/JohnMorales/dotfiles/master/colors/24-bit-color.sh

Alright so I compiled rxvt with that patch and the script works as expected, but still todoman does not show colored listnames.

**Comment by potuz** [comment] 2018-09-15 12:47
My bad! I  was being hit by #298 as well. Deleted the cache and all is fine now.

**Comment by dmp1ce** [comment] 2018-11-28 20:22
For those wondering, like I was, the cache is probably located in `~/.cache/todoman`. I deleted that directory after running `vdirsyncer metasync`. Then color worked for display names.

**Comment by WhyNotHugo** [comment] 2018-11-28 20:35
Gosh, looks like I kinda abandoned #299. It just needs some tests and should be done, I'll see when I have a few spare minutes.
