### ISSUE TITLE
how do I create a new recurring task

### ISSUE THREAD

**Issue by agaAdams** [pimutils/todoman#423] opened 2021-01-12 15:08 UTC
Hi everybody,

how do I create a new recurring task with todoman. I understand that I cannot edit the recurrence of an item with the edit dialogue. But how do I create a new item via command line with an recurrence?

Sorry if this has been answered in the docs, but I somehow can't figure this out.

Cheers

aga

**Comment by WhyNotHugo** [comment] 2021-01-15 17:31
Creating recurring events is also not supported (although completing one will automatically create the next one in the series).

I usually create recurring events on my phone, and keep in sync via vdirsyncer. Another option is to manually copy the `RRULE` into the file, but that's really a big hack and prone to breakage.

Gonna leave this open, since this needs to be implemented at some point.

**Comment by agaAdams** [comment] 2021-01-16 11:02
Ah, many thanks then for the clarification. The workaround via phone works obviously.

**Comment by WhyNotHugo** [comment] 2022-04-21 07:58
This is a duplicate of #305

**Closed by WhyNotHugo** 2022-04-21 07:58 UTC
Labels: enhancement, contributions welcome
