### ISSUE TITLE
Homebrew test block fails with 3.1.0

### ISSUE THREAD

**Issue by ilovezfs** [pimutils/todoman#235] opened 2017-04-18 06:40 UTC
See
https://github.com/Homebrew/homebrew-core/pull/12581
https://bot.brew.sh/job/Homebrew%20Core%20Pull%20Requests/63/version=sierra/console
```
  test do
    ENV["LC_ALL"] = "en_US.UTF-8"
    (testpath/".config/todoman/todoman.conf").write <<-EOS.undent
      [main]
      path = #{testpath}/.calendar/*
      date_format = %Y-%m-%d
      default_list = Personal
    EOS
    (testpath/".calendar/Personal").mkpath
    system "#{bin}/todo", "new", "newtodo"
    assert_match "newtodo", shell_output("#{bin}/todo list")
  end
```
fails with the error
```
iMac-TMP:homebrew-core joe$ brew test todoman -vd
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/todoman.rb
Testing todoman
==> Using the sandbox
/usr/bin/sandbox-exec -f /tmp/homebrew20170417-58560-74t3z5.sb /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -W0 -I /usr/local/Homebrew/Library/Homebrew -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/todoman.rb -vd
/usr/local/Homebrew/Library/Homebrew/test.rb (Formulary::FromPathLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/todoman.rb
==> /usr/local/Cellar/todoman/3.1.0/bin/todo new newtodo
Traceback (most recent call last):
  File "/usr/local/Cellar/todoman/3.1.0/libexec/lib/python3.6/site-packages/configobj.py", line 1942, in _handle_configspec
    _inspec=True)
  File "/usr/local/Cellar/todoman/3.1.0/libexec/lib/python3.6/site-packages/configobj.py", line 1229, in __init__
    self._load(infile, configspec)
  File "/usr/local/Cellar/todoman/3.1.0/libexec/lib/python3.6/site-packages/configobj.py", line 1240, in _load
    raise IOError('Config file not found: "%s".' % self.filename)
OSError: Config file not found: "/usr/local/Cellar/todoman/3.1.0/libexec/lib/python3.6/site-packages/todoman/confspec.ini".

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/todoman/3.1.0/bin/todo", line 11, in <module>
    load_entry_point('todoman==3.1.0', 'console_scripts', 'todo')()
  File "/usr/local/Cellar/todoman/3.1.0/libexec/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/Cellar/todoman/3.1.0/libexec/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/Cellar/todoman/3.1.0/libexec/lib/python3.6/site-packages/click/core.py", line 1063, in invoke
    Command.invoke(self, ctx)
  File "/usr/local/Cellar/todoman/3.1.0/libexec/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/Cellar/todoman/3.1.0/libexec/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Cellar/todoman/3.1.0/libexec/lib/python3.6/site-packages/click_log/core.py", line 94, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/Cellar/todoman/3.1.0/libexec/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/Cellar/todoman/3.1.0/libexec/lib/python3.6/site-packages/todoman/cli.py", line 31, in wrapper
    return f(*a, **kw)
  File "/usr/local/Cellar/todoman/3.1.0/libexec/lib/python3.6/site-packages/todoman/cli.py", line 213, in cli
    ctx.config = load_config()
  File "/usr/local/Cellar/todoman/3.1.0/libexec/lib/python3.6/site-packages/todoman/configuration.py", line 81, in load_config
    config = ConfigObj(path, configspec=specpath, file_error=True)
  File "/usr/local/Cellar/todoman/3.1.0/libexec/lib/python3.6/site-packages/configobj.py", line 1229, in __init__
    self._load(infile, configspec)
  File "/usr/local/Cellar/todoman/3.1.0/libexec/lib/python3.6/site-packages/configobj.py", line 1325, in _load
    self._handle_configspec(configspec)
  File "/usr/local/Cellar/todoman/3.1.0/libexec/lib/python3.6/site-packages/configobj.py", line 1948, in _handle_configspec
    raise IOError('Reading configspec failed: %s' % e)
OSError: Reading configspec failed: Config file not found: "/usr/local/Cellar/todoman/3.1.0/libexec/lib/python3.6/site-packages/todoman/confspec.ini".
/usr/local/Homebrew/Library/Homebrew/debrew.rb:11:in `raise'
BuildError: Failed executing: /usr/local/Cellar/todoman/3.1.0/bin/todo new newtodo
1. raise
2. ignore
3. backtrace
4. irb
5. shell
```

@hobarrera Any idea what the problem might be?

**Comment by hobarrera** [comment] 2017-04-18 13:23
It's a packaging bug, sorry. For some reason `confspec.ini` isn't getting packaged any more.

**Comment by ilovezfs** [comment] 2017-04-18 13:29
@hobarrera thanks for taking a look.

**Comment by hobarrera** [comment] 2017-04-18 13:42
Okay, so both packages (source and wheel) have the missing file, but installing them doesn't include them. I'm not sure if *we* broke something, or a dependency did, since nothing seems to have change in that field.

**Comment by untitaker** [comment] 2017-04-18 13:42
I don't understand why it was ever packaged. You need a MANIFEST.in for that.

**Comment by hobarrera** [comment] 2017-04-18 13:42
It was packaged thanks to `setuptools-scm`. It's still being packaged, but not being installed.

**Comment by untitaker** [comment] 2017-04-18 13:44
As far as I understand setuptools-scm is only responsible for the versioning, not that.

**Comment by ilovezfs** [comment] 2017-04-18 13:49
It also now affects the existing 3.0.1 formula, which has its pypi deps pinned.

**Comment by hobarrera** [comment] 2017-04-18 13:52
> It also now affects the existing 3.0.1 formula, which has its pypi deps pinned.

Can you tell me exactly what depends are pinned? Did this formula work before? Does it have `setuptools_scm`pinned (I guess the first question answers this)?

> As far as I understand setuptools-scm is only responsible for the versioning, not that.

Yes, it does. Try using `git add` on a file, installing a package, and compare that to the file just sitting there. See `FILES_COMMAND`.

**Comment by hobarrera** [comment] 2017-04-18 13:53
FWIW, installing from the git repo works (eg: `confspec.ini` is installed).

**Comment by untitaker** [comment] 2017-04-18 14:01
Wow, I didn't sign up for that... good to know

**Comment by ilovezfs** [comment] 2017-04-18 14:03
>Can you tell me exactly what depends are pinned?

For 3.0.1
https://github.com/Homebrew/homebrew-core/blob/master/Formula/todoman.rb#L18-L86

>Did this formula work before?

Yes the current bottle passes the test block.

**Comment by ilovezfs** [comment] 2017-04-18 14:17
If I manually
```
cp todoman/confspec.ini /usr/local/Cellar/todoman/3.0.1/libexec/lib/python3.6/site-packages/todoman/
```
Then it works.

So
```
/usr/local/Cellar/todoman/3.0.1/libexec/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-6e5muzeu-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-sk94gfyw-record/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/Cellar/todoman/3.0.1/libexec/bin/../include/site/python3.6/todoman
```
isn't copying it over there for some reason on its own.

**Comment by ilovezfs** [comment] 2017-04-18 14:27
So it works if I use
```
python3 -c import setuptools... --no-user-cfg install --prefix=/usr/local/Cellar/todoman/3.0.1/libexec --single-version-externally-managed --record=installed.txt
```
instead of pip3 in the virtualenv.

CC @tdsmith

**Comment by ilovezfs** [comment] 2017-04-18 14:44
@hobarrera OK so it seems to be specific to using a virtualenv. I can reproduce this outside of Homebrew when in a virtualenv.

```
(venv) iMac-TMP:todoman-venv joe$ pip3 install todoman
Collecting todoman
  Using cached todoman-3.1.0-py3-none-any.whl
Collecting python-dateutil (from todoman)
  Using cached python_dateutil-2.6.0-py2.py3-none-any.whl
Collecting icalendar (from todoman)
  Using cached icalendar-3.11.3-py2.py3-none-any.whl
Collecting atomicwrites (from todoman)
  Using cached atomicwrites-1.1.5-py2.py3-none-any.whl
Collecting click>=6.0 (from todoman)
  Using cached click-6.7-py2.py3-none-any.whl
Collecting tabulate (from todoman)
  Using cached tabulate-0.7.7-py2.py3-none-any.whl
Collecting humanize (from todoman)
Collecting click-log>=0.1.3 (from todoman)
  Using cached click_log-0.1.8-py2.py3-none-any.whl
Collecting parsedatetime (from todoman)
Collecting urwid (from todoman)
Collecting configobj (from todoman)
Collecting pyxdg (from todoman)
Requirement already satisfied: six>=1.5 in ./venv/lib/python3.6/site-packages (from python-dateutil->todoman)
Collecting pytz (from icalendar->todoman)
  Using cached pytz-2017.2-py2.py3-none-any.whl
Collecting future (from parsedatetime->todoman)
Installing collected packages: python-dateutil, pytz, icalendar, atomicwrites, click, tabulate, humanize, click-log, future, parsedatetime, urwid, configobj, pyxdg, todoman
Successfully installed atomicwrites-1.1.5 click-6.7 click-log-0.1.8 configobj-5.0.6 future-0.16.0 humanize-0.5.1 icalendar-3.11.3 parsedatetime-2.3 python-dateutil-2.6.0 pytz-2017.2 pyxdg-0.25 tabulate-0.7.7 todoman-3.1.0 urwid-1.3.1
(venv) iMac-TMP:todoman-venv joe$ find .|grep confspec
./venv/lib/python3.6/site-packages/todoman/confspec.ini
(venv) iMac-TMP:todoman-venv joe$ pip3 uninstall todoman
Uninstalling todoman-3.1.0:
  /Users/joe/todoman-venv/venv/bin/todo
  /Users/joe/todoman-venv/venv/lib/python3.6/site-packages/todoman-3.1.0.dist-info/DESCRIPTION.rst
  /Users/joe/todoman-venv/venv/lib/python3.6/site-packages/todoman-3.1.0.dist-info/INSTALLER
  /Users/joe/todoman-venv/venv/lib/python3.6/site-packages/todoman-3.1.0.dist-info/METADATA
  /Users/joe/todoman-venv/venv/lib/python3.6/site-packages/todoman-3.1.0.dist-info/RECORD
  /Users/joe/todoman-venv/venv/lib/python3.6/site-packages/todoman-3.1.0.dist-info/WHEEL
  /Users/joe/todoman-venv/venv/lib/python3.6/site-packages/todoman-3.1.0.dist-info/entry_points.txt
  /Users/joe/todoman-venv/venv/lib/python3.6/site-packages/todoman-3.1.0.dist-info/metadata.json
  /Users/joe/todoman-venv/venv/lib/python3.6/site-packages/todoman-3.1.0.dist-info/top_level.txt
  /Users/joe/todoman-venv/venv/lib/python3.6/site-packages/todoman/__init__.py
  /Users/joe/todoman-venv/venv/lib/python3.6/site-packages/todoman/__main__.py
  /Users/joe/todoman-venv/venv/lib/python3.6/site-packages/todoman/__pycache__/__init__.cpython-36.pyc
  /Users/joe/todoman-venv/venv/lib/python3.6/site-packages/todoman/__pycache__/__main__.cpython-36.pyc
  /Users/joe/todoman-venv/venv/lib/python3.6/site-packages/todoman/__pycache__/cli.cpython-36.pyc
  /Users/joe/todoman-venv/venv/lib/python3.6/site-packages/todoman/__pycache__/configuration.cpython-36.pyc
  /Users/joe/todoman-venv/venv/lib/python3.6/site-packages/todoman/__pycache__/exceptions.cpython-36.pyc
  /Users/joe/todoman-venv/venv/lib/python3.6/site-packages/todoman/__pycache__/formatters.cpython-36.pyc
  /Users/joe/todoman-venv/venv/lib/python3.6/site-packages/todoman/__pycache__/interactive.cpython-36.pyc
  /Users/joe/todoman-venv/venv/lib/python3.6/site-packages/todoman/__pycache__/model.cpython-36.pyc
  /Users/joe/todoman-venv/venv/lib/python3.6/site-packages/todoman/__pycache__/version.cpython-36.pyc
  /Users/joe/todoman-venv/venv/lib/python3.6/site-packages/todoman/__pycache__/widgets.cpython-36.pyc
  /Users/joe/todoman-venv/venv/lib/python3.6/site-packages/todoman/cli.py
  /Users/joe/todoman-venv/venv/lib/python3.6/site-packages/todoman/configuration.py
  /Users/joe/todoman-venv/venv/lib/python3.6/site-packages/todoman/confspec.ini
  /Users/joe/todoman-venv/venv/lib/python3.6/site-packages/todoman/exceptions.py
  /Users/joe/todoman-venv/venv/lib/python3.6/site-packages/todoman/formatters.py
  /Users/joe/todoman-venv/venv/lib/python3.6/site-packages/todoman/interactive.py
  /Users/joe/todoman-venv/venv/lib/python3.6/site-packages/todoman/model.py
  /Users/joe/todoman-venv/venv/lib/python3.6/site-packages/todoman/version.py
  /Users/joe/todoman-venv/venv/lib/python3.6/site-packages/todoman/widgets.py
Proceed (y/n)? y
  Successfully uninstalled todoman-3.1.0
(venv) iMac-TMP:todoman-venv joe$ find .|grep confspec
(venv) iMac-TMP:todoman-venv joe$ pip3 install --no-binary :all: todoman
Collecting todoman
  Using cached todoman-3.1.0.tar.gz
Requirement already satisfied: atomicwrites in ./venv/lib/python3.6/site-packages (from todoman)
Requirement already satisfied: click>=6.0 in ./venv/lib/python3.6/site-packages (from todoman)
Requirement already satisfied: click_log>=0.1.3 in ./venv/lib/python3.6/site-packages (from todoman)
Requirement already satisfied: configobj in ./venv/lib/python3.6/site-packages (from todoman)
Requirement already satisfied: humanize in ./venv/lib/python3.6/site-packages (from todoman)
Requirement already satisfied: icalendar in ./venv/lib/python3.6/site-packages (from todoman)
Requirement already satisfied: parsedatetime in ./venv/lib/python3.6/site-packages (from todoman)
Requirement already satisfied: python-dateutil in ./venv/lib/python3.6/site-packages (from todoman)
Requirement already satisfied: pyxdg in ./venv/lib/python3.6/site-packages (from todoman)
Requirement already satisfied: tabulate in ./venv/lib/python3.6/site-packages (from todoman)
Requirement already satisfied: urwid in ./venv/lib/python3.6/site-packages (from todoman)
Requirement already satisfied: six in ./venv/lib/python3.6/site-packages (from configobj->todoman)
Requirement already satisfied: pytz in ./venv/lib/python3.6/site-packages (from icalendar->todoman)
Requirement already satisfied: future in ./venv/lib/python3.6/site-packages (from parsedatetime->todoman)
Skipping bdist_wheel for todoman, due to binaries being disabled for it.
Installing collected packages: todoman
  Running setup.py install for todoman ... done
Successfully installed todoman-3.1.0
(venv) iMac-TMP:todoman-venv joe$ find .|grep confspec
(venv) iMac-TMP:todoman-venv joe$
```

**Comment by hobarrera** [comment] 2017-04-19 00:35
Building the `PKGBUILD` for previous versions on Arch (including `2.1.0` and `v3.0.1`) yields the same broken installation, so this it most likely a broken dependency (I'm suspecting `setuptools-scm`, will try this later today).

**Comment by hobarrera** [comment] 2017-04-19 17:13
A bit more of this was discussed [here](https://github.com/pypa/setuptools_scm/issues/143#issuecomment-295255499). Apparently, a `setuptools` bug. :(

**Comment by hobarrera** [comment] 2017-04-19 18:23
This was an [upstream issue](https://github.com/pypa/setuptools/issues/1016) for setuptools-35.0.0, and has been fixed in 35.0.1.

**Closed by hobarrera** 2017-04-19 18:23 UTC
Labels: bug

**Comment by ilovezfs** [comment] 2017-04-19 18:46
@hobarrera yep! If I upgrade the vendored setuptools in the Homebrew python3 formula, then the todoman test block passes. Thanks for your help!

**Comment by ilovezfs** [comment] 2017-04-19 18:57
Oh ... actually it seems to have spontaneously resolved without even doing that. @hobarrera was this a server side bug?

**Comment by hobarrera** [comment] 2017-04-19 19:16
Nope, no server side change relevant here. You don't have setuptools pinned for the above linked formula, so maybe it always uses the latest version?

**Comment by hobarrera** [comment] 2017-04-19 19:17
Oh, creating a virtualenv will install setuptools onto it. Not sure if it uses the system on, or the latest one, so maybe that affects the build/install too.

**Comment by ilovezfs** [comment] 2017-04-19 19:19
In any case, I've shipped the new version! Thanks again.
https://github.com/Homebrew/homebrew-core/commit/10086c130d02a0f80afcaaea232d956dc00c1283
https://github.com/Homebrew/homebrew-core/commit/2f6b0d048a698203a20effb0d399d0efb9e01602

**Comment by hobarrera** [comment] 2017-04-20 04:33
Thank you for reporting this. You picked this up way before I did.

**Comment by legrostdg** [comment] 2017-05-17 13:35
I ran into the same problem while making a Debian package for `todoman`. I'm not sure I understand the problem: do I need to make sure Debian gets `setuptools-35.0.0` or do you need to make a new release containing `confspec.ini`?

**Comment by hobarrera** [comment] 2017-05-17 13:52
@legrostdg 35.0.0 is broken. You just need to make sure you **don't** use that version. 35.0.1 provided a fix for the regression.

**Comment by legrostdg** [comment] 2017-05-17 13:59
Sorry, I meant `setuptools-35.0.1`. Debian has `setuptools-33.1.1`, and I ran into the same problem... Don't you have to make a release which contains `confspec.ini` (Debian packages are based on upstream tarballs)?

**Comment by hobarrera** [comment] 2017-05-17 14:27
All the packages contained confspec.ini. Setuptools 35.0.0 didn't install them (due to a bug in that specific release).

If your seeing an error with another setuptools version, it's probably another bug, even though it looks similar.

**Comment by legrostdg** [comment] 2017-05-17 15:20
OK, I managed to fix the problem, it was an issue with Debian's pybuild. Thanks!

**Comment by hobarrera** [comment] 2017-05-17 16:33
Cool! Thanks for taking the time to package this. Let me know when it's done and I con add it to the docs.

Also, make sure you check the [Notes for Packagers](https://todoman.readthedocs.io/en/stable/install.html#notes-for-packagers).
